import { Hub, Truck, StaffShipment, Cargo } from "./types";

export function getFreshSeedData(baseTime: number = Date.now()): {
  hubs: Hub[];
  trucks: Truck[];
  shipments: StaffShipment[];
  cargo: Cargo[];
} {
  const baseMs = baseTime;

  const hubs: Hub[] = [
    { id: "HUB-HYD", name: "Hyderabad", code: "HYD", lat: 17.385, lon: 78.4867, state: "Telangana", isOperational: true },
    { id: "HUB-BLR", name: "Bengaluru", code: "BLR", lat: 12.9716, lon: 77.5946, state: "Karnataka", isOperational: true },
    { id: "HUB-CHN", name: "Chennai", code: "CHN", lat: 13.0827, lon: 80.2707, state: "Tamil Nadu", isOperational: true },
    { id: "HUB-MUM", name: "Mumbai", code: "MUM", lat: 19.076, lon: 72.8777, state: "Maharashtra", isOperational: true },
    { id: "HUB-PUN", name: "Pune", code: "PUN", lat: 18.5204, lon: 73.8567, state: "Maharashtra", isOperational: true },
    { id: "HUB-DEL", name: "Delhi", code: "DEL", lat: 28.6139, lon: 77.209, state: "Delhi NCR", isOperational: true },
    { id: "HUB-KOL", name: "Kolkata", code: "KOL", lat: 22.5726, lon: 88.3639, state: "West Bengal", isOperational: true },
    { id: "HUB-NAG", name: "Nagpur", code: "NAG", lat: 21.1458, lon: 79.0882, state: "Maharashtra", isOperational: true },
  ];

  const trucks: Truck[] = [
    {
      id: "TRK-001",
      numberPlate: "TS 09 AB 2048",
      driverName: "Ravi Kumar",
      driverMobile: "+91 98765 43210",
      copassengerName: "Arjun Rao",
      copassengerMobile: "+91 98765 43211",
      currentLocation: "Bengaluru",
      destination: "Chennai",
      capacity: 1200,
      availableCapacity: 380,
      maxVolume: 35,
      availableVolume: 12.5,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-001-1",
          fromNode: "Bengaluru",
          toNode: "Chennai",
          departureTime: new Date(baseMs + 1 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 6 * 3600000).toISOString(),
          distanceKm: 350,
        },
      ],
    },
    {
      id: "TRK-007",
      numberPlate: "KA 03 MN 4422",
      driverName: "Sanjay Verma",
      driverMobile: "+91 98111 22334",
      copassengerName: "Mohan Lal",
      copassengerMobile: "+91 98111 22335",
      currentLocation: "Bengaluru",
      destination: "Chennai",
      capacity: 1400,
      availableCapacity: 450,
      maxVolume: 40,
      availableVolume: 15.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-007-1",
          fromNode: "Bengaluru",
          toNode: "Chennai",
          departureTime: new Date(baseMs + 2.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 8 * 3600000).toISOString(),
          distanceKm: 350,
        },
      ],
    },
    {
      id: "TRK-002",
      numberPlate: "MH 04 CD 1122",
      driverName: "Suresh Patil",
      driverMobile: "+91 87654 32109",
      copassengerName: "Vikram Desai",
      copassengerMobile: "+91 87654 32110",
      currentLocation: "Pune",
      destination: "Bengaluru",
      capacity: 2000,
      availableCapacity: 650,
      maxVolume: 45,
      availableVolume: 18.0,
      status: "In Transit",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-002-1",
          fromNode: "Pune",
          toNode: "Hyderabad",
          departureTime: new Date(baseMs + 1 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 7 * 3600000).toISOString(),
          distanceKm: 560,
        },
        {
          segmentId: "SEG-002-2",
          fromNode: "Hyderabad",
          toNode: "Bengaluru",
          departureTime: new Date(baseMs + 8 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 14 * 3600000).toISOString(),
          distanceKm: 570,
        },
      ],
    },
    {
      id: "TRK-003",
      numberPlate: "TN 07 EF 3344",
      driverName: "Karthik Rajan",
      driverMobile: "+91 76543 21098",
      copassengerName: "Mohan Subramanian",
      copassengerMobile: "+91 76543 21099",
      currentLocation: "Hyderabad",
      destination: "Chennai",
      capacity: 1500,
      availableCapacity: 450,
      maxVolume: 40,
      availableVolume: 14.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-003-1",
          fromNode: "Hyderabad",
          toNode: "Chennai",
          departureTime: new Date(baseMs + 2 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 10 * 3600000).toISOString(),
          distanceKm: 630,
        },
      ],
    },
    {
      id: "TRK-004",
      numberPlate: "KA 01 GH 5566",
      driverName: "Praveen Shetty",
      driverMobile: "+91 65432 10987",
      copassengerName: "Anand Gowda",
      copassengerMobile: "+91 65432 10988",
      currentLocation: "Bengaluru",
      destination: "Mumbai",
      capacity: 2500,
      availableCapacity: 800,
      maxVolume: 60,
      availableVolume: 22.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-004-1",
          fromNode: "Bengaluru",
          toNode: "Pune",
          departureTime: new Date(baseMs + 1.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 9 * 3600000).toISOString(),
          distanceKm: 840,
        },
        {
          segmentId: "SEG-004-2",
          fromNode: "Pune",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 10 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 13 * 3600000).toISOString(),
          distanceKm: 150,
        },
      ],
    },
    {
      id: "TRK-005",
      numberPlate: "WB 02 IJ 7788",
      driverName: "Amit Ghosh",
      driverMobile: "+91 54321 09876",
      copassengerName: "Debashish Roy",
      copassengerMobile: "+91 54321 09877",
      currentLocation: "Nagpur",
      destination: "Chennai",
      capacity: 3000,
      availableCapacity: 920,
      maxVolume: 70,
      availableVolume: 28.0,
      status: "In Transit",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-005-1",
          fromNode: "Nagpur",
          toNode: "Hyderabad",
          departureTime: new Date(baseMs + 1 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 7 * 3600000).toISOString(),
          distanceKm: 500,
        },
        {
          segmentId: "SEG-005-2",
          fromNode: "Hyderabad",
          toNode: "Chennai",
          departureTime: new Date(baseMs + 8 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 15 * 3600000).toISOString(),
          distanceKm: 630,
        },
      ],
    },
    {
      id: "TRK-006",
      numberPlate: "DL 01 JK 9900",
      driverName: "Harpreet Singh",
      driverMobile: "+91 91234 56789",
      copassengerName: "Gurdeep Singh",
      copassengerMobile: "+91 91234 56790",
      currentLocation: "Delhi",
      destination: "Hyderabad",
      capacity: 3500,
      availableCapacity: 1400,
      maxVolume: 80,
      availableVolume: 35.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-006-1",
          fromNode: "Delhi",
          toNode: "Nagpur",
          departureTime: new Date(baseMs + 2 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 14 * 3600000).toISOString(),
          distanceKm: 1050,
        },
        {
          segmentId: "SEG-006-2",
          fromNode: "Nagpur",
          toNode: "Hyderabad",
          departureTime: new Date(baseMs + 15 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 22 * 3600000).toISOString(),
          distanceKm: 500,
        },
      ],
    },
    {
      id: "TRK-008",
      numberPlate: "DL 04 EF 6677",
      driverName: "Vikram Malhotra",
      driverMobile: "+91 98100 54321",
      copassengerName: "Ramesh Yadav",
      copassengerMobile: "+91 98100 54322",
      currentLocation: "Delhi",
      destination: "Mumbai",
      capacity: 3200,
      availableCapacity: 1100,
      maxVolume: 45,
      availableVolume: 16.5,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-008-1",
          fromNode: "Delhi",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 1.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 16 * 3600000).toISOString(),
          distanceKm: 1420,
        },
      ],
    },
    {
      id: "TRK-009",
      numberPlate: "MH 02 KL 8899",
      driverName: "Deepak Sharma",
      driverMobile: "+91 97233 44556",
      copassengerName: "Sunil Verma",
      copassengerMobile: "+91 97233 44557",
      currentLocation: "Delhi",
      destination: "Mumbai",
      capacity: 2800,
      availableCapacity: 950,
      maxVolume: 40,
      availableVolume: 14.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-009-1",
          fromNode: "Delhi",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 3.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 18.5 * 3600000).toISOString(),
          distanceKm: 1420,
        },
      ],
    },
    {
      id: "TRK-010",
      numberPlate: "RJ 14 GH 3344",
      driverName: "Manish Choudhary",
      driverMobile: "+91 94140 12345",
      copassengerName: "Ajay Singh",
      copassengerMobile: "+91 94140 12346",
      currentLocation: "Delhi",
      destination: "Pune",
      capacity: 3500,
      availableCapacity: 1200,
      maxVolume: 50,
      availableVolume: 20.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-010-1",
          fromNode: "Delhi",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 2 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 17 * 3600000).toISOString(),
          distanceKm: 1420,
        },
        {
          segmentId: "SEG-010-2",
          fromNode: "Mumbai",
          toNode: "Pune",
          departureTime: new Date(baseMs + 18 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 21 * 3600000).toISOString(),
          distanceKm: 150,
        },
      ],
    },
    {
      id: "TRK-011",
      numberPlate: "MH 31 PQ 5511",
      driverName: "Nitin Deshmukh",
      driverMobile: "+91 98222 33445",
      copassengerName: "Kiran Patil",
      copassengerMobile: "+91 98222 33446",
      currentLocation: "Nagpur",
      destination: "Mumbai",
      capacity: 2600,
      availableCapacity: 850,
      maxVolume: 42,
      availableVolume: 15.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-011-1",
          fromNode: "Nagpur",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 15 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 24 * 3600000).toISOString(),
          distanceKm: 820,
        },
      ],
    },
  ];

  const shipments: StaffShipment[] = [
    {
      id: "SHP-2048",
      code: "PGB-HYD-2048-X7",
      cargoId: "CRG-78431",
      origin: "Hyderabad",
      destination: "Chennai",
      priority: "High",
      weight: 42,
      volume: 0.8,
      deadline: new Date(baseMs + 18 * 3600000).toISOString(),
      status: "Misplaced",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Bengaluru",
      plannedRoute: ["Hyderabad", "Chennai"],
      disruptionReason: "Misrouted during cross-dock sorting at Hyderabad; diverted to Bengaluru Hub",
      disruptionTimestamp: new Date(baseMs - 0.5 * 3600000).toISOString(),
    },
    {
      id: "SHP-2049",
      code: "PGB-MUM-2049-K3",
      cargoId: "CRG-78432",
      origin: "Mumbai",
      destination: "Bengaluru",
      priority: "Medium",
      weight: 120,
      volume: 2.4,
      deadline: new Date(baseMs + 24 * 3600000).toISOString(),
      status: "In Transit",
      assignedTruck: "TRK-002",
      assignedRoute: "RT-03",
      currentLocation: "Pune",
      plannedRoute: ["Mumbai", "Pune", "Bengaluru"],
    },
    {
      id: "SHP-2050",
      code: "PGB-DEL-2050-R1",
      cargoId: "CRG-78433",
      origin: "Delhi",
      destination: "Mumbai",
      priority: "Medium",
      weight: 18,
      volume: 0.3,
      deadline: new Date(baseMs + 36 * 3600000).toISOString(),
      status: "Misplaced",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Delhi",
      plannedRoute: ["Delhi", "Mumbai"],
      disruptionReason: "Scheduled carrier cancelled linehaul departure at Delhi Cross-dock Terminal",
      disruptionTimestamp: new Date(baseMs - 0.5 * 3600000).toISOString(),
    },
    {
      id: "SHP-2051",
      code: "PGB-HYD-2051-M5",
      cargoId: "CRG-78434",
      origin: "Hyderabad",
      destination: "Chennai",
      priority: "High",
      weight: 65,
      volume: 1.2,
      deadline: new Date(baseMs + 20 * 3600000).toISOString(),
      status: "Misplaced",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Hyderabad",
      plannedRoute: ["Hyderabad", "Chennai"],
      disruptionReason: "Carrier missed departure window due to maintenance holdup",
      disruptionTimestamp: new Date(baseMs - 1 * 3600000).toISOString(),
    },
    {
      id: "SHP-2052",
      code: "PGB-CHN-2052-A9",
      cargoId: "CRG-78435",
      origin: "Chennai",
      destination: "Delhi",
      priority: "Medium",
      weight: 30,
      volume: 0.6,
      deadline: new Date(baseMs + 48 * 3600000).toISOString(),
      status: "Recovered",
      assignedTruck: "TRK-003",
      assignedRoute: "RT-05",
      currentLocation: "Chennai",
      plannedRoute: ["Chennai", "Delhi"],
    },
    {
      id: "SHP-2053",
      code: "PGB-PUN-2053-B2",
      cargoId: "CRG-78436",
      origin: "Pune",
      destination: "Hyderabad",
      priority: "Low",
      weight: 8,
      volume: 0.15,
      deadline: new Date(baseMs + 30 * 3600000).toISOString(),
      status: "Pending",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Pune",
      plannedRoute: ["Pune", "Hyderabad"],
    },
  ];

  const cargo: Cargo[] = [
    {
      id: "CRG-78431",
      shipmentId: "SHP-2048",
      description: "Critical Semiconductor Components",
      weight: 42,
      volume: 0.8,
      origin: "Hyderabad",
      destination: "Chennai",
      priority: "High",
      specialHandling: "Anti-Static / Fragile",
      status: "Misrouted",
    },
    {
      id: "CRG-78432",
      shipmentId: "SHP-2049",
      description: "Textile Rolls",
      weight: 120,
      volume: 2.4,
      origin: "Mumbai",
      destination: "Bengaluru",
      priority: "Medium",
      specialHandling: "None",
      status: "In Transit",
    },
    {
      id: "CRG-78433",
      shipmentId: "SHP-2050",
      description: "Office Supplies",
      weight: 18,
      volume: 0.3,
      origin: "Delhi",
      destination: "Mumbai",
      priority: "Low",
      specialHandling: "None",
      status: "Pending",
    },
    {
      id: "CRG-78434",
      shipmentId: "SHP-2051",
      description: "Emergency Vaccine Diagnostic Kits",
      weight: 65,
      volume: 1.2,
      origin: "Hyderabad",
      destination: "Chennai",
      priority: "High",
      specialHandling: "Temperature Controlled (2-8°C)",
      status: "Pending",
    },
    {
      id: "CRG-78435",
      shipmentId: "SHP-2052",
      description: "Precision Auto Alternators",
      weight: 30,
      volume: 0.6,
      origin: "Chennai",
      destination: "Delhi",
      priority: "Medium",
      specialHandling: "None",
      status: "Delivered",
    },
    {
      id: "CRG-78436",
      shipmentId: "SHP-2053",
      description: "Engineering Documentation",
      weight: 8,
      volume: 0.15,
      origin: "Pune",
      destination: "Hyderabad",
      priority: "Low",
      specialHandling: "None",
      status: "Pending",
    },
  ];

  return { hubs, trucks, shipments, cargo };
}

const initialSeed = getFreshSeedData();
export const SEED_HUBS: Hub[] = initialSeed.hubs;
export const SEED_TRUCKS: Truck[] = initialSeed.trucks;
export const SEED_SHIPMENTS: StaffShipment[] = initialSeed.shipments;
export const SEED_CARGO: Cargo[] = initialSeed.cargo;
