import { Hub, Truck, StaffShipment, Cargo } from "./types";

export function getFreshSeedData(baseTime: number = Date.now()): {
  hubs: Hub[];
  trucks: Truck[];
  shipments: StaffShipment[];
  cargo: Cargo[];
} {
  const baseMs = baseTime;

  const hubs: Hub[] = [
    { id: "HUB-HYD", name: "Hyderabad", code: "HYD", lat: 17.385, lon: 78.4867, state: "Telangana", isOperational: true },
    { id: "HUB-BLR", name: "Bengaluru", code: "BLR", lat: 12.9716, lon: 77.5946, state: "Karnataka", isOperational: true },
    { id: "HUB-CHN", name: "Chennai", code: "CHN", lat: 13.0827, lon: 80.2707, state: "Tamil Nadu", isOperational: true },
    { id: "HUB-MUM", name: "Mumbai", code: "MUM", lat: 19.076, lon: 72.8777, state: "Maharashtra", isOperational: true },
    { id: "HUB-PUN", name: "Pune", code: "PUN", lat: 18.5204, lon: 73.8567, state: "Maharashtra", isOperational: true },
    { id: "HUB-DEL", name: "Delhi", code: "DEL", lat: 28.6139, lon: 77.209, state: "Delhi NCR", isOperational: true },
    { id: "HUB-KOL", name: "Kolkata", code: "KOL", lat: 22.5726, lon: 88.3639, state: "West Bengal", isOperational: true },
    { id: "HUB-NAG", name: "Nagpur", code: "NAG", lat: 21.1458, lon: 79.0882, state: "Maharashtra", isOperational: true },
    { id: "HUB-AMD", name: "Ahmedabad", code: "AMD", lat: 23.0225, lon: 72.5714, state: "Gujarat", isOperational: true },
    { id: "HUB-JAI", name: "Jaipur", code: "JAI", lat: 26.9124, lon: 75.7873, state: "Rajasthan", isOperational: true },
    { id: "HUB-LKO", name: "Lucknow", code: "LKO", lat: 26.8467, lon: 80.9462, state: "Uttar Pradesh", isOperational: true },
    { id: "HUB-PAT", name: "Patna", code: "PAT", lat: 25.5941, lon: 85.1376, state: "Bihar", isOperational: true },
    { id: "HUB-GAU", name: "Guwahati", code: "GAU", lat: 26.1445, lon: 91.7362, state: "Assam", isOperational: true },
    { id: "HUB-BBI", name: "Bhubaneswar", code: "BBI", lat: 20.2961, lon: 85.8245, state: "Odisha", isOperational: true },
    { id: "HUB-COK", name: "Kochi", code: "COK", lat: 9.9312, lon: 76.2673, state: "Kerala", isOperational: true },
    { id: "HUB-VTZ", name: "Visakhapatnam", code: "VTZ", lat: 17.6868, lon: 83.2185, state: "Andhra Pradesh", isOperational: true },
    { id: "HUB-IDR", name: "Indore", code: "IDR", lat: 22.7196, lon: 75.8577, state: "Madhya Pradesh", isOperational: true },
    { id: "HUB-CHD", name: "Chandigarh", code: "CHD", lat: 30.7333, lon: 76.7794, state: "Punjab", isOperational: true },
    { id: "HUB-BHO", name: "Bhopal", code: "BHO", lat: 23.2599, lon: 77.4126, state: "Madhya Pradesh", isOperational: true },
    { id: "HUB-CJB", name: "Coimbatore", code: "CJB", lat: 11.0168, lon: 76.9558, state: "Tamil Nadu", isOperational: true },
  ];

  const trucks: Truck[] = [
    {
      id: "TRK-001",
      numberPlate: "TS 09 AB 2048",
      driverName: "Ravi Kumar",
      driverMobile: "+91 98765 43210",
      copassengerName: "Arjun Rao",
      copassengerMobile: "+91 98765 43211",
      currentLocation: "Bengaluru",
      destination: "Chennai",
      capacity: 1200,
      availableCapacity: 380,
      maxVolume: 35,
      availableVolume: 12.5,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-001-1",
          fromNode: "Bengaluru",
          toNode: "Chennai",
          departureTime: new Date(baseMs + 1 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 6 * 3600000).toISOString(),
          distanceKm: 350,
        },
      ],
    },
    {
      id: "TRK-007",
      numberPlate: "KA 03 MN 4422",
      driverName: "Sanjay Verma",
      driverMobile: "+91 98111 22334",
      copassengerName: "Mohan Lal",
      copassengerMobile: "+91 98111 22335",
      currentLocation: "Bengaluru",
      destination: "Chennai",
      capacity: 1400,
      availableCapacity: 450,
      maxVolume: 40,
      availableVolume: 15.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-007-1",
          fromNode: "Bengaluru",
          toNode: "Chennai",
          departureTime: new Date(baseMs + 2.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 8 * 3600000).toISOString(),
          distanceKm: 350,
        },
      ],
    },
    {
      id: "TRK-002",
      numberPlate: "MH 04 CD 1122",
      driverName: "Suresh Patil",
      driverMobile: "+91 87654 32109",
      copassengerName: "Vikram Desai",
      copassengerMobile: "+91 87654 32110",
      currentLocation: "Pune",
      destination: "Bengaluru",
      capacity: 2000,
      availableCapacity: 650,
      maxVolume: 45,
      availableVolume: 18.0,
      status: "In Transit",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-002-1",
          fromNode: "Pune",
          toNode: "Hyderabad",
          departureTime: new Date(baseMs + 1 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 7 * 3600000).toISOString(),
          distanceKm: 560,
        },
        {
          segmentId: "SEG-002-2",
          fromNode: "Hyderabad",
          toNode: "Bengaluru",
          departureTime: new Date(baseMs + 8 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 14 * 3600000).toISOString(),
          distanceKm: 570,
        },
      ],
    },
    {
      id: "TRK-003",
      numberPlate: "TN 07 EF 3344",
      driverName: "Karthik Rajan",
      driverMobile: "+91 76543 21098",
      copassengerName: "Mohan Subramanian",
      copassengerMobile: "+91 76543 21099",
      currentLocation: "Hyderabad",
      destination: "Chennai",
      capacity: 1500,
      availableCapacity: 450,
      maxVolume: 40,
      availableVolume: 14.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-003-1",
          fromNode: "Hyderabad",
          toNode: "Chennai",
          departureTime: new Date(baseMs + 2 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 10 * 3600000).toISOString(),
          distanceKm: 630,
        },
      ],
    },
    {
      id: "TRK-004",
      numberPlate: "KA 01 GH 5566",
      driverName: "Praveen Shetty",
      driverMobile: "+91 65432 10987",
      copassengerName: "Anand Gowda",
      copassengerMobile: "+91 65432 10988",
      currentLocation: "Bengaluru",
      destination: "Mumbai",
      capacity: 2500,
      availableCapacity: 800,
      maxVolume: 60,
      availableVolume: 22.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-004-1",
          fromNode: "Bengaluru",
          toNode: "Pune",
          departureTime: new Date(baseMs + 1.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 9 * 3600000).toISOString(),
          distanceKm: 840,
        },
        {
          segmentId: "SEG-004-2",
          fromNode: "Pune",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 10 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 13 * 3600000).toISOString(),
          distanceKm: 150,
        },
      ],
    },
    {
      id: "TRK-005",
      numberPlate: "WB 02 IJ 7788",
      driverName: "Amit Ghosh",
      driverMobile: "+91 54321 09876",
      copassengerName: "Debashish Roy",
      copassengerMobile: "+91 54321 09877",
      currentLocation: "Nagpur",
      destination: "Chennai",
      capacity: 3000,
      availableCapacity: 920,
      maxVolume: 70,
      availableVolume: 28.0,
      status: "In Transit",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-005-1",
          fromNode: "Nagpur",
          toNode: "Hyderabad",
          departureTime: new Date(baseMs + 1 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 7 * 3600000).toISOString(),
          distanceKm: 500,
        },
        {
          segmentId: "SEG-005-2",
          fromNode: "Hyderabad",
          toNode: "Chennai",
          departureTime: new Date(baseMs + 8 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 15 * 3600000).toISOString(),
          distanceKm: 630,
        },
      ],
    },
    {
      id: "TRK-006",
      numberPlate: "DL 01 JK 9900",
      driverName: "Harpreet Singh",
      driverMobile: "+91 91234 56789",
      copassengerName: "Gurdeep Singh",
      copassengerMobile: "+91 91234 56790",
      currentLocation: "Delhi",
      destination: "Hyderabad",
      capacity: 3500,
      availableCapacity: 1400,
      maxVolume: 80,
      availableVolume: 35.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-006-1",
          fromNode: "Delhi",
          toNode: "Nagpur",
          departureTime: new Date(baseMs + 2 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 14 * 3600000).toISOString(),
          distanceKm: 1050,
        },
        {
          segmentId: "SEG-006-2",
          fromNode: "Nagpur",
          toNode: "Hyderabad",
          departureTime: new Date(baseMs + 15 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 22 * 3600000).toISOString(),
          distanceKm: 500,
        },
      ],
    },
    {
      id: "TRK-008",
      numberPlate: "DL 04 EF 6677",
      driverName: "Vikram Malhotra",
      driverMobile: "+91 98100 54321",
      copassengerName: "Ramesh Yadav",
      copassengerMobile: "+91 98100 54322",
      currentLocation: "Delhi",
      destination: "Mumbai",
      capacity: 3200,
      availableCapacity: 1100,
      maxVolume: 45,
      availableVolume: 16.5,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-008-1",
          fromNode: "Delhi",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 1.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 16 * 3600000).toISOString(),
          distanceKm: 1420,
        },
      ],
    },
    {
      id: "TRK-009",
      numberPlate: "MH 02 KL 8899",
      driverName: "Deepak Sharma",
      driverMobile: "+91 97233 44556",
      copassengerName: "Sunil Verma",
      copassengerMobile: "+91 97233 44557",
      currentLocation: "Delhi",
      destination: "Mumbai",
      capacity: 2800,
      availableCapacity: 950,
      maxVolume: 40,
      availableVolume: 14.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-009-1",
          fromNode: "Delhi",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 3.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 18.5 * 3600000).toISOString(),
          distanceKm: 1420,
        },
      ],
    },
    {
      id: "TRK-010",
      numberPlate: "RJ 14 GH 3344",
      driverName: "Manish Choudhary",
      driverMobile: "+91 94140 12345",
      copassengerName: "Ajay Singh",
      copassengerMobile: "+91 94140 12346",
      currentLocation: "Delhi",
      destination: "Pune",
      capacity: 3500,
      availableCapacity: 1200,
      maxVolume: 50,
      availableVolume: 20.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-010-1",
          fromNode: "Delhi",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 2 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 17 * 3600000).toISOString(),
          distanceKm: 1420,
        },
        {
          segmentId: "SEG-010-2",
          fromNode: "Mumbai",
          toNode: "Pune",
          departureTime: new Date(baseMs + 18 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 21 * 3600000).toISOString(),
          distanceKm: 150,
        },
      ],
    },
    {
      id: "TRK-011",
      numberPlate: "MH 31 PQ 5511",
      driverName: "Nitin Deshmukh",
      driverMobile: "+91 98222 33445",
      copassengerName: "Kiran Patil",
      copassengerMobile: "+91 98222 33446",
      currentLocation: "Nagpur",
      destination: "Mumbai",
      capacity: 2600,
      availableCapacity: 850,
      maxVolume: 42,
      availableVolume: 15.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-011-1",
          fromNode: "Nagpur",
          toNode: "Mumbai",
          departureTime: new Date(baseMs + 15 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 24 * 3600000).toISOString(),
          distanceKm: 820,
        },
      ],
    },
    {
      id: "TRK-012",
      numberPlate: "CH 01 TA 7711",
      driverName: "Jasbir Singh",
      driverMobile: "+91 98140 77112",
      copassengerName: "Kuldeep Gill",
      copassengerMobile: "+91 98140 77113",
      currentLocation: "Delhi",
      destination: "Chandigarh",
      capacity: 2400,
      availableCapacity: 920,
      maxVolume: 40,
      availableVolume: 16.5,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-012-1",
          fromNode: "Delhi",
          toNode: "Chandigarh",
          departureTime: new Date(baseMs + 1 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 5.5 * 3600000).toISOString(),
          distanceKm: 250,
        },
      ],
    },
    {
      id: "TRK-013",
      numberPlate: "RJ 14 GA 3399",
      driverName: "Mahendra Rathore",
      driverMobile: "+91 94142 33991",
      copassengerName: "Gopal Sharma",
      copassengerMobile: "+91 94142 33992",
      currentLocation: "Delhi",
      destination: "Ahmedabad",
      capacity: 3200,
      availableCapacity: 1100,
      maxVolume: 55,
      availableVolume: 21.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-013-1",
          fromNode: "Delhi",
          toNode: "Jaipur",
          departureTime: new Date(baseMs + 2 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 7 * 3600000).toISOString(),
          distanceKm: 280,
        },
        {
          segmentId: "SEG-013-2",
          fromNode: "Jaipur",
          toNode: "Ahmedabad",
          departureTime: new Date(baseMs + 8 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 19 * 3600000).toISOString(),
          distanceKm: 670,
        },
      ],
    },
    {
      id: "TRK-014",
      numberPlate: "GJ 01 CX 8822",
      driverName: "Bhavin Patel",
      driverMobile: "+91 98250 88221",
      copassengerName: "Hitesh Shah",
      copassengerMobile: "+91 98250 88222",
      currentLocation: "Mumbai",
      destination: "Ahmedabad",
      capacity: 2800,
      availableCapacity: 750,
      maxVolume: 45,
      availableVolume: 17.5,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-014-1",
          fromNode: "Mumbai",
          toNode: "Ahmedabad",
          departureTime: new Date(baseMs + 3 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 11 * 3600000).toISOString(),
          distanceKm: 530,
        },
      ],
    },
    {
      id: "TRK-015",
      numberPlate: "UP 32 BK 5544",
      driverName: "Rakesh Tiwari",
      driverMobile: "+91 94500 55441",
      copassengerName: "Manoj Yadav",
      copassengerMobile: "+91 94500 55442",
      currentLocation: "Delhi",
      destination: "Patna",
      capacity: 3400,
      availableCapacity: 1250,
      maxVolume: 60,
      availableVolume: 24.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-015-1",
          fromNode: "Delhi",
          toNode: "Lucknow",
          departureTime: new Date(baseMs + 1.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 10 * 3600000).toISOString(),
          distanceKm: 550,
        },
        {
          segmentId: "SEG-015-2",
          fromNode: "Lucknow",
          toNode: "Patna",
          departureTime: new Date(baseMs + 11.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 21 * 3600000).toISOString(),
          distanceKm: 540,
        },
      ],
    },
    {
      id: "TRK-016",
      numberPlate: "WB 19 DL 6677",
      driverName: "Subhash Banerjee",
      driverMobile: "+91 98300 66771",
      copassengerName: "Tarun Das",
      copassengerMobile: "+91 98300 66772",
      currentLocation: "Kolkata",
      destination: "Lucknow",
      capacity: 3000,
      availableCapacity: 950,
      maxVolume: 50,
      availableVolume: 19.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-016-1",
          fromNode: "Kolkata",
          toNode: "Patna",
          departureTime: new Date(baseMs + 2.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 12 * 3600000).toISOString(),
          distanceKm: 580,
        },
        {
          segmentId: "SEG-016-2",
          fromNode: "Patna",
          toNode: "Lucknow",
          departureTime: new Date(baseMs + 13.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 23 * 3600000).toISOString(),
          distanceKm: 540,
        },
      ],
    },
    {
      id: "TRK-017",
      numberPlate: "AS 01 EK 9911",
      driverName: "Pranab Saikia",
      driverMobile: "+91 94350 99111",
      copassengerName: "Biren Gogoi",
      copassengerMobile: "+91 94350 99112",
      currentLocation: "Kolkata",
      destination: "Guwahati",
      capacity: 3200,
      availableCapacity: 1300,
      maxVolume: 55,
      availableVolume: 22.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-017-1",
          fromNode: "Kolkata",
          toNode: "Guwahati",
          departureTime: new Date(baseMs + 3 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 22 * 3600000).toISOString(),
          distanceKm: 990,
        },
      ],
    },
    {
      id: "TRK-018",
      numberPlate: "TN 09 FY 4433",
      driverName: "Senthil Nathan",
      driverMobile: "+91 98400 44331",
      copassengerName: "Velu Pandian",
      copassengerMobile: "+91 98400 44332",
      currentLocation: "Chennai",
      destination: "Kolkata",
      capacity: 3500,
      availableCapacity: 1150,
      maxVolume: 65,
      availableVolume: 25.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-018-1",
          fromNode: "Chennai",
          toNode: "Visakhapatnam",
          departureTime: new Date(baseMs + 1 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 14 * 3600000).toISOString(),
          distanceKm: 800,
        },
        {
          segmentId: "SEG-018-2",
          fromNode: "Visakhapatnam",
          toNode: "Bhubaneswar",
          departureTime: new Date(baseMs + 15 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 22 * 3600000).toISOString(),
          distanceKm: 440,
        },
        {
          segmentId: "SEG-018-3",
          fromNode: "Bhubaneswar",
          toNode: "Kolkata",
          departureTime: new Date(baseMs + 23 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 30 * 3600000).toISOString(),
          distanceKm: 440,
        },
      ],
    },
    {
      id: "TRK-019",
      numberPlate: "AP 31 TH 2288",
      driverName: "Chiranjeevi Rao",
      driverMobile: "+91 98480 22881",
      copassengerName: "Srinivas Naidu",
      copassengerMobile: "+91 98480 22882",
      currentLocation: "Hyderabad",
      destination: "Visakhapatnam",
      capacity: 2600,
      availableCapacity: 820,
      maxVolume: 42,
      availableVolume: 15.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-019-1",
          fromNode: "Hyderabad",
          toNode: "Visakhapatnam",
          departureTime: new Date(baseMs + 2 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 12 * 3600000).toISOString(),
          distanceKm: 620,
        },
      ],
    },
    {
      id: "TRK-020",
      numberPlate: "KL 07 GP 1155",
      driverName: "Mathew Varghese",
      driverMobile: "+91 98470 11551",
      copassengerName: "Jithin Thomas",
      copassengerMobile: "+91 98470 11552",
      currentLocation: "Bengaluru",
      destination: "Kochi",
      capacity: 2500,
      availableCapacity: 780,
      maxVolume: 40,
      availableVolume: 16.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-020-1",
          fromNode: "Bengaluru",
          toNode: "Coimbatore",
          departureTime: new Date(baseMs + 1 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 7 * 3600000).toISOString(),
          distanceKm: 360,
        },
        {
          segmentId: "SEG-020-2",
          fromNode: "Coimbatore",
          toNode: "Kochi",
          departureTime: new Date(baseMs + 8 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 12.5 * 3600000).toISOString(),
          distanceKm: 190,
        },
      ],
    },
    {
      id: "TRK-021",
      numberPlate: "MP 09 HZ 7744",
      driverName: "Dharmendra Chouhan",
      driverMobile: "+91 98260 77441",
      copassengerName: "Vijay Solanki",
      copassengerMobile: "+91 98260 77442",
      currentLocation: "Indore",
      destination: "Nagpur",
      capacity: 2800,
      availableCapacity: 880,
      maxVolume: 45,
      availableVolume: 17.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-021-1",
          fromNode: "Indore",
          toNode: "Bhopal",
          departureTime: new Date(baseMs + 1.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 5.5 * 3600000).toISOString(),
          distanceKm: 195,
        },
        {
          segmentId: "SEG-021-2",
          fromNode: "Bhopal",
          toNode: "Nagpur",
          departureTime: new Date(baseMs + 6.5 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 13.5 * 3600000).toISOString(),
          distanceKm: 350,
        },
      ],
    },
    {
      id: "TRK-022",
      numberPlate: "GJ 05 JK 9933",
      driverName: "Pravin Solanki",
      driverMobile: "+91 98240 99331",
      copassengerName: "Ketan Desai",
      copassengerMobile: "+91 98240 99332",
      currentLocation: "Ahmedabad",
      destination: "Indore",
      capacity: 2600,
      availableCapacity: 900,
      maxVolume: 42,
      availableVolume: 15.5,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-022-1",
          fromNode: "Ahmedabad",
          toNode: "Indore",
          departureTime: new Date(baseMs + 2 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 9 * 3600000).toISOString(),
          distanceKm: 390,
        },
      ],
    },
    {
      id: "TRK-023",
      numberPlate: "OD 02 LM 8866",
      driverName: "Debasis Mohanty",
      driverMobile: "+91 94370 88661",
      copassengerName: "Sanjay Jena",
      copassengerMobile: "+91 94370 88662",
      currentLocation: "Bhubaneswar",
      destination: "Nagpur",
      capacity: 3200,
      availableCapacity: 1050,
      maxVolume: 50,
      availableVolume: 20.0,
      status: "Available",
      currentDelayMinutes: 0,
      schedule: [
        {
          segmentId: "SEG-023-1",
          fromNode: "Bhubaneswar",
          toNode: "Nagpur",
          departureTime: new Date(baseMs + 3 * 3600000).toISOString(),
          arrivalTime: new Date(baseMs + 18 * 3600000).toISOString(),
          distanceKm: 830,
        },
      ],
    },
  ];

  const shipments: StaffShipment[] = [
    {
      id: "SHP-2048",
      code: "PGB-HYD-2048-X7",
      cargoId: "CRG-78431",
      origin: "Hyderabad",
      destination: "Chennai",
      priority: "High",
      weight: 42,
      volume: 0.8,
      deadline: new Date(baseMs + 18 * 3600000).toISOString(),
      status: "Misplaced",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Bengaluru",
      plannedRoute: ["Hyderabad", "Chennai"],
      disruptionReason: "Misrouted during cross-dock sorting at Hyderabad; diverted to Bengaluru Hub",
      disruptionTimestamp: new Date(baseMs - 0.5 * 3600000).toISOString(),
    },
    {
      id: "SHP-2049",
      code: "PGB-MUM-2049-K3",
      cargoId: "CRG-78432",
      origin: "Mumbai",
      destination: "Bengaluru",
      priority: "Medium",
      weight: 120,
      volume: 2.4,
      deadline: new Date(baseMs + 24 * 3600000).toISOString(),
      status: "In Transit",
      assignedTruck: "TRK-002",
      assignedRoute: "RT-03",
      currentLocation: "Pune",
      plannedRoute: ["Mumbai", "Pune", "Bengaluru"],
    },
    {
      id: "SHP-2050",
      code: "PGB-DEL-2050-R1",
      cargoId: "CRG-78433",
      origin: "Delhi",
      destination: "Mumbai",
      priority: "Medium",
      weight: 18,
      volume: 0.3,
      deadline: new Date(baseMs + 36 * 3600000).toISOString(),
      status: "Misplaced",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Delhi",
      plannedRoute: ["Delhi", "Mumbai"],
      disruptionReason: "Scheduled carrier cancelled linehaul departure at Delhi Cross-dock Terminal",
      disruptionTimestamp: new Date(baseMs - 0.5 * 3600000).toISOString(),
    },
    {
      id: "SHP-2051",
      code: "PGB-HYD-2051-M5",
      cargoId: "CRG-78434",
      origin: "Hyderabad",
      destination: "Chennai",
      priority: "High",
      weight: 65,
      volume: 1.2,
      deadline: new Date(baseMs + 20 * 3600000).toISOString(),
      status: "Misplaced",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Hyderabad",
      plannedRoute: ["Hyderabad", "Chennai"],
      disruptionReason: "Carrier missed departure window due to maintenance holdup",
      disruptionTimestamp: new Date(baseMs - 1 * 3600000).toISOString(),
    },
    {
      id: "SHP-2052",
      code: "PGB-CHN-2052-A9",
      cargoId: "CRG-78435",
      origin: "Chennai",
      destination: "Delhi",
      priority: "Medium",
      weight: 30,
      volume: 0.6,
      deadline: new Date(baseMs + 48 * 3600000).toISOString(),
      status: "Recovered",
      assignedTruck: "TRK-003",
      assignedRoute: "RT-05",
      currentLocation: "Chennai",
      plannedRoute: ["Chennai", "Delhi"],
    },
    {
      id: "SHP-2053",
      code: "PGB-PUN-2053-B2",
      cargoId: "CRG-78436",
      origin: "Pune",
      destination: "Hyderabad",
      priority: "Low",
      weight: 8,
      volume: 0.15,
      deadline: new Date(baseMs + 30 * 3600000).toISOString(),
      status: "Pending",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Pune",
      plannedRoute: ["Pune", "Hyderabad"],
    },
    {
      id: "SHP-2056",
      code: "PGB-AMD-2056-X1",
      cargoId: "CRG-78437",
      origin: "Ahmedabad",
      destination: "Kolkata",
      priority: "High",
      weight: 85,
      volume: 1.5,
      deadline: new Date(baseMs + 28 * 3600000).toISOString(),
      status: "Misplaced",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Jaipur",
      plannedRoute: ["Ahmedabad", "Nagpur", "Kolkata"],
      disruptionReason: "Cross-dock sorting error at Ahmedabad; stranded at Jaipur Hub",
      disruptionTimestamp: new Date(baseMs - 0.7 * 3600000).toISOString(),
    },
    {
      id: "SHP-2057",
      code: "PGB-CHD-2057-C4",
      cargoId: "CRG-78438",
      origin: "Chandigarh",
      destination: "Bengaluru",
      priority: "Medium",
      weight: 60,
      volume: 1.1,
      deadline: new Date(baseMs + 36 * 3600000).toISOString(),
      status: "Misplaced",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Delhi",
      plannedRoute: ["Chandigarh", "Delhi", "Bengaluru"],
      disruptionReason: "Transshipment delay at Delhi hub terminal gate",
      disruptionTimestamp: new Date(baseMs - 0.4 * 3600000).toISOString(),
    },
    {
      id: "SHP-2058",
      code: "PGB-COK-2058-K9",
      cargoId: "CRG-78439",
      origin: "Kochi",
      destination: "Delhi",
      priority: "High",
      weight: 50,
      volume: 0.9,
      deadline: new Date(baseMs + 32 * 3600000).toISOString(),
      status: "Misplaced",
      assignedTruck: null,
      assignedRoute: null,
      currentLocation: "Coimbatore",
      plannedRoute: ["Kochi", "Coimbatore", "Hyderabad", "Delhi"],
      disruptionReason: "Feeder shuttle breakdown between Kochi and Coimbatore",
      disruptionTimestamp: new Date(baseMs - 0.8 * 3600000).toISOString(),
    },
  ];

  const cargo: Cargo[] = [
    {
      id: "CRG-78431",
      shipmentId: "SHP-2048",
      description: "Critical Semiconductor Components",
      weight: 42,
      volume: 0.8,
      origin: "Hyderabad",
      destination: "Chennai",
      priority: "High",
      specialHandling: "Anti-Static / Fragile",
      status: "Misrouted",
    },
    {
      id: "CRG-78432",
      shipmentId: "SHP-2049",
      description: "Textile Rolls",
      weight: 120,
      volume: 2.4,
      origin: "Mumbai",
      destination: "Bengaluru",
      priority: "Medium",
      specialHandling: "None",
      status: "In Transit",
    },
    {
      id: "CRG-78433",
      shipmentId: "SHP-2050",
      description: "Office Supplies",
      weight: 18,
      volume: 0.3,
      origin: "Delhi",
      destination: "Mumbai",
      priority: "Low",
      specialHandling: "None",
      status: "Pending",
    },
    {
      id: "CRG-78434",
      shipmentId: "SHP-2051",
      description: "Emergency Vaccine Diagnostic Kits",
      weight: 65,
      volume: 1.2,
      origin: "Hyderabad",
      destination: "Chennai",
      priority: "High",
      specialHandling: "Temperature Controlled (2-8°C)",
      status: "Pending",
    },
    {
      id: "CRG-78435",
      shipmentId: "SHP-2052",
      description: "Precision Auto Alternators",
      weight: 30,
      volume: 0.6,
      origin: "Chennai",
      destination: "Delhi",
      priority: "Medium",
      specialHandling: "None",
      status: "Delivered",
    },
    {
      id: "CRG-78436",
      shipmentId: "SHP-2053",
      description: "Engineering Documentation",
      weight: 8,
      volume: 0.15,
      origin: "Pune",
      destination: "Hyderabad",
      priority: "Low",
      specialHandling: "None",
      status: "Pending",
    },
    {
      id: "CRG-78437",
      shipmentId: "SHP-2056",
      description: "High-Density Lithium EV Battery Packs",
      weight: 85,
      volume: 1.5,
      origin: "Ahmedabad",
      destination: "Kolkata",
      priority: "High",
      specialHandling: "Hazardous / Class 9",
      status: "Pending",
    },
    {
      id: "CRG-78438",
      shipmentId: "SHP-2057",
      description: "Precision Aerospace Avionics",
      weight: 60,
      volume: 1.1,
      origin: "Chandigarh",
      destination: "Bengaluru",
      priority: "Medium",
      specialHandling: "Anti-Static / Fragile",
      status: "Pending",
    },
    {
      id: "CRG-78439",
      shipmentId: "SHP-2058",
      description: "Pharmaceutical Active Ingredients",
      weight: 50,
      volume: 0.9,
      origin: "Kochi",
      destination: "Delhi",
      priority: "High",
      specialHandling: "Temperature Controlled (15-25°C)",
      status: "Pending",
    },
  ];

  return { hubs, trucks, shipments, cargo };
}

const initialSeed = getFreshSeedData();
export const SEED_HUBS: Hub[] = initialSeed.hubs;
export const SEED_TRUCKS: Truck[] = initialSeed.trucks;
export const SEED_SHIPMENTS: StaffShipment[] = initialSeed.shipments;
export const SEED_CARGO: Cargo[] = initialSeed.cargo;
