import { stateManager } from "../lib/engine/state-manager";

function assert(condition: boolean, message: string): asserts condition {
  if (!condition) {
    console.error(`\x1b[31m✗ [ASSERTION FAILED]\x1b[0m ${message}`);
    throw new Error(`Assertion failed: ${message}`);
  }
  console.log(`  \x1b[32m✓ [ASSERTION PASSED]\x1b[0m ${message}`);
}

async function verifyRecoveryPipeline() {
  console.log("========================================================================");
  console.log("  PIGGYBACK APPLICATION RUNTIME VERIFICATION");
  console.log("  Strict Assertion Suite for Primary Plan, Shadow Fallback & Replanning");
  console.log("========================================================================\n");

  // ──────────────────────────────────────────────────────────────────────────
  // SCENARIO 1: Feasible High-Availability Recovery (SHP-2048)
  // ──────────────────────────────────────────────────────────────────────────
  console.log(`========================================================================`);
  console.log(`[SCENARIO 1: FEASIBLE HIGH-AVAILABILITY CORRIDOR (SHP-2048)]`);
  console.log(`========================================================================`);

  const shipmentId = "SHP-2048";
  const initialShipment = stateManager.getShipment(shipmentId);
  assert(initialShipment !== undefined, `Target shipment [${shipmentId}] must exist in state manager`);
  assert(initialShipment.status === "Misplaced", `Shipment [${shipmentId}] must be in Misplaced status`);
  console.log(`  • ID:          ${initialShipment.id} (${initialShipment.origin} -> ${initialShipment.destination})`);
  console.log(`  • Current Hub: ${initialShipment.currentLocation} | Weight: ${initialShipment.weight} kg`);

  // Solve Recovery
  console.log(`\n  [1.1 Solving Recovery for ${shipmentId}]`);
  const solveResult1 = stateManager.solveRecovery(shipmentId);
  const receipt1 = solveResult1.receipt;
  const plans1 = stateManager.getPlans(shipmentId);

  assert(receipt1 !== undefined, "Decision receipt must be generated by solver");
  assert(receipt1.feasibleCandidatesCount > 0, "Solver must discover at least 1 feasible candidate");
  assert(receipt1.totalCandidatesEvaluated > 0, "Solver must evaluate positive candidate corridors");

  // Verify status matches solver's intended behavior (OPTIMAL for on-time SLA compliance, FEASIBLE otherwise)
  assert(
    receipt1.status === "OPTIMAL" || receipt1.status === "FEASIBLE",
    `Solver must return OPTIMAL or FEASIBLE status for feasible scenario (got: ${receipt1.status})`
  );

  // 1.2 Primary Plan Validation
  console.log(`\n  [1.2 Validating Primary Recovery Plan]`);
  const primaryPlan = plans1.find((p) => p.strategy === "PRIMARY");
  assert(primaryPlan !== undefined, "Primary recovery plan MUST be generated and non-null");
  assert(primaryPlan.strategy === "PRIMARY", "Primary plan must explicitly carry PRIMARY strategy");
  assert(typeof primaryPlan.vehicleId === "string" && primaryPlan.vehicleId.length > 0, "Primary plan must have a valid assigned vehicle");
  assert(primaryPlan.slaMarginMinutes >= 0, `Primary plan must satisfy delivery deadline (margin: ${primaryPlan.slaMarginMinutes} min)`);
  assert(primaryPlan.incrementalCost > 0, `Primary plan must calculate positive incremental cost (₹${primaryPlan.incrementalCost})`);
  assert(typeof primaryPlan.co2SavedKg === "number" && primaryPlan.co2SavedKg > 0, "Primary plan must compute positive carbon avoidance");

  // When on-time, solver status MUST strictly be OPTIMAL
  if (primaryPlan.slaMarginMinutes >= 0 && (primaryPlan.candidate?.delayMinutes ?? 0) <= 0) {
    assert(receipt1.status === "OPTIMAL", `On-time plan satisfying SLA must yield OPTIMAL solver status (got: ${receipt1.status})`);
  }

  // Savings assertion matching solver economics: positive savings required whenever charter exceeds piggyback
  assert(
    typeof primaryPlan.costSavingsPercent === "number" && primaryPlan.costSavingsPercent >= 0,
    `Primary plan cost savings must be non-negative (got: ${primaryPlan.costSavingsPercent}%)`
  );
  if (primaryPlan.baselineCharterCost !== undefined && primaryPlan.baselineCharterCost > primaryPlan.incrementalCost) {
    assert(
      typeof primaryPlan.costSavingsPercent === "number" && primaryPlan.costSavingsPercent > 0,
      `Primary plan must achieve positive savings when charter (₹${primaryPlan.baselineCharterCost}) exceeds piggyback (₹${primaryPlan.incrementalCost}) (got: ${primaryPlan.costSavingsPercent}%)`
    );
  }

  console.log(`  • Primary Vehicle:      ${primaryPlan.vehicleId}`);
  console.log(`  • Corridor:             ${primaryPlan.pickupHub} -> ${primaryPlan.dropoffHub}`);
  console.log(`  • SLA Safety Buffer:    +${primaryPlan.slaMarginMinutes} min`);
  console.log(`  • Savings vs Charter:   ${primaryPlan.costSavingsPercent}% (₹${primaryPlan.incrementalCost} vs ₹${primaryPlan.baselineCharterCost})`);

  // 1.3 Shadow Hot-Standby Validation
  console.log(`\n  [1.3 Validating Shadow Hot-Standby Plan]`);
  const shadowPlan = plans1.find((p) => p.strategy === "SHADOW");
  assert(shadowPlan !== undefined, "Shadow hot-standby plan MUST be generated and non-null");
  assert(shadowPlan.strategy === "SHADOW", "Shadow plan must explicitly carry SHADOW strategy");
  assert(shadowPlan.vehicleId !== primaryPlan.vehicleId, "Shadow plan must utilize a non-identical vehicle fleet asset");
  assert(shadowPlan.shadowGuarantee !== undefined, "Shadow plan must carry a quantified shadow guarantee audit");
  assert(
    shadowPlan.shadowGuarantee.guarantee === "EDGE_DISJOINT" || shadowPlan.shadowGuarantee.guarantee === "PENALIZED_OVERLAP",
    `Shadow guarantee must be EDGE_DISJOINT or PENALIZED_OVERLAP (got: ${shadowPlan.shadowGuarantee.guarantee})`
  );
  assert(typeof shadowPlan.shadowGuarantee.overlapPercentage === "number", "Shadow plan must quantify overlap percentage");

  console.log(`  • Shadow Vehicle:       ${shadowPlan.vehicleId}`);
  console.log(`  • Fallback Guarantee:   ${shadowPlan.shadowGuarantee.guarantee} (${shadowPlan.shadowGuarantee.overlapPercentage}% overlap)`);

  // 1.4 Dynamic Replanning Validation
  console.log(`\n  [1.4 Dynamic Replanning & Explicit Strategy Verification]`);
  console.log(`  • Triggering Re-optimization for ${shipmentId}...`);
  stateManager.reoptimize(shipmentId);
  const reoptimizedPlans = stateManager.getPlans(shipmentId);
  const reoptimizedReceipt = stateManager.getReceipt(shipmentId);

  assert(reoptimizedReceipt !== undefined, "Replanning must generate a new decision receipt");
  assert(typeof reoptimizedReceipt.hash === "string" && reoptimizedReceipt.hash.startsWith("0x"), "Decision receipt hash must be valid 256-bit hex string starting with 0x");
  assert(reoptimizedReceipt.hash.length === 66, "Decision receipt hash must be exactly 66 chars (0x + 64 hex characters)");

  // Explicitly verify returned plans include both PRIMARY and SHADOW strategies
  assert(reoptimizedPlans.length >= 2, `Dynamic replanning must reproduce at least 2 active recovery plans (got: ${reoptimizedPlans.length})`);
  const replannedPrimary = reoptimizedPlans.find((p) => p.strategy === "PRIMARY");
  const replannedShadow = reoptimizedPlans.find((p) => p.strategy === "SHADOW");

  assert(replannedPrimary !== undefined, "Dynamic replanning must explicitly return a PRIMARY strategy plan");
  assert(replannedShadow !== undefined, "Dynamic replanning must explicitly return a SHADOW strategy plan");
  assert(replannedPrimary.strategy === "PRIMARY", "Replanned primary plan must have strategy PRIMARY");
  assert(replannedShadow.strategy === "SHADOW", "Replanned shadow plan must have strategy SHADOW");
  assert(typeof replannedPrimary.vehicleId === "string" && replannedPrimary.vehicleId.length > 0, "Replanned primary plan must have a valid vehicle ID");
  assert(typeof replannedShadow.vehicleId === "string" && replannedShadow.vehicleId.length > 0, "Replanned shadow plan must have a valid vehicle ID");
  assert(replannedShadow.vehicleId !== replannedPrimary.vehicleId, "Replanned shadow plan must utilize a separate vehicle asset from primary");

  console.log(`  • Replanned Plans:      ${reoptimizedPlans.length} plans (PRIMARY: ${replannedPrimary.vehicleId}, SHADOW: ${replannedShadow.vehicleId})`);
  console.log(`  • Receipt Hash:         ${reoptimizedReceipt.hash}`);

  // ──────────────────────────────────────────────────────────────────────────
  // SCENARIO 2: Feasible Regional Corridor (SHP-2051)
  // ──────────────────────────────────────────────────────────────────────────
  console.log(`\n========================================================================`);
  console.log(`[SCENARIO 2: FEASIBLE REGIONAL RECOVERY CORRIDOR (SHP-2051)]`);
  console.log(`========================================================================`);

  const scenario2Id = "SHP-2051";
  const solveResult2 = stateManager.solveRecovery(scenario2Id);
  const receipt2 = solveResult2.receipt;
  const plans2 = stateManager.getPlans(scenario2Id);

  assert(receipt2 !== undefined, `Decision receipt must exist for scenario ${scenario2Id}`);
  assert(receipt2.status === "OPTIMAL" || receipt2.status === "FEASIBLE", `Solver status must be OPTIMAL or FEASIBLE for ${scenario2Id} (got: ${receipt2.status})`);
  const scenario2Primary = plans2.find((p) => p.strategy === "PRIMARY");
  const scenario2Shadow = plans2.find((p) => p.strategy === "SHADOW");
  assert(scenario2Primary !== undefined, `Scenario ${scenario2Id} must yield a PRIMARY recovery plan`);
  assert(scenario2Shadow !== undefined, `Scenario ${scenario2Id} must yield a SHADOW recovery plan`);
  assert(scenario2Primary.strategy === "PRIMARY", `Scenario ${scenario2Id} primary must have strategy PRIMARY`);
  assert(scenario2Shadow.strategy === "SHADOW", `Scenario ${scenario2Id} shadow must have strategy SHADOW`);
  assert(
    typeof scenario2Primary.costSavingsPercent === "number" && scenario2Primary.costSavingsPercent > 0,
    `Scenario ${scenario2Id} must achieve positive cost savings vs charter (got: ${scenario2Primary.costSavingsPercent}%)`
  );

  // ──────────────────────────────────────────────────────────────────────────
  // SCENARIO 3: Infeasible / Disrupted Corridor Handled Gracefully (SHP-2050)
  // ──────────────────────────────────────────────────────────────────────────
  console.log(`\n========================================================================`);
  console.log(`[SCENARIO 3: CONSTRAINED / ZERO-CAPACITY CORRIDOR (SHP-2050)]`);
  console.log(`========================================================================`);

  const scenario3Id = "SHP-2050";
  const solveResult3 = stateManager.solveRecovery(scenario3Id);
  const receipt3 = solveResult3.receipt;
  const plans3 = stateManager.getPlans(scenario3Id);

  assert(receipt3 !== undefined, `Decision receipt must exist for constrained scenario ${scenario3Id}`);
  assert(
    receipt3.status === "NO_FEASIBLE_PIGGYBACK",
    `Solver must return NO_FEASIBLE_PIGGYBACK when no valid piggyback options exist (got: ${receipt3.status})`
  );
  assert(receipt3.feasibleCandidatesCount === 0, `Feasible candidate count must be 0 for unrecoverable corridor (got: ${receipt3.feasibleCandidatesCount})`);
  assert(plans3.length === 0, `No spurious plans should be retained for infeasible recovery (got: ${plans3.length} plans)`);

  console.log(`  • Handled Status:       ${receipt3.status}`);
  console.log(`  • Feasible Options:     ${receipt3.feasibleCandidatesCount} (properly flagged as unrecoverable)`);

  console.log("\n========================================================================");
  console.log("  ALL RUNTIME ASSERTIONS PASSED ACROSS ALL TEST SCENARIOS!");
  console.log("  Explicit PRIMARY and SHADOW strategies confirmed for replanning.");
  console.log("  Solver OPTIMAL/FEASIBLE/NO_FEASIBLE status & economic savings validated.");
  console.log("========================================================================");
}

verifyRecoveryPipeline().catch((err) => {
  console.error("\nFATAL ASSERTION ERROR:", err.message);
  process.exit(1);
});
