import { stateManager } from "../lib/engine/state-manager";

function assert(condition: boolean, message: string): asserts condition {
  if (!condition) {
    console.error(`\x1b[31m✗ [ASSERTION FAILED]\x1b[0m ${message}`);
    throw new Error(`Assertion failed: ${message}`);
  }
  console.log(`  \x1b[32m✓ [ASSERTION PASSED]\x1b[0m ${message}`);
}

async function verifyRecoveryPipeline() {
  console.log("========================================================================");
  console.log("  PIGGYBACK APPLICATION RUNTIME VERIFICATION");
  console.log("  Strict Assertion Suite for Primary Plan, Shadow Fallback & Replanning");
  console.log("========================================================================\n");

  const shipmentId = "SHP-2048";

  // 1. Initial State Assertion
  console.log(`[1. SHIPMENT CONTEXT]`);
  const initialShipment = stateManager.getShipment(shipmentId);
  assert(initialShipment !== undefined, `Target shipment [${shipmentId}] must exist in state manager`);
  assert(initialShipment.status === "Misplaced", `Shipment [${shipmentId}] must be in Misplaced status`);
  console.log(`  • ID:          ${initialShipment.id}`);
  console.log(`  • Status:      ${initialShipment.status}`);
  console.log(`  • Route:       ${initialShipment.origin} -> ${initialShipment.destination}`);
  console.log(`  • Weight/Vol:  ${initialShipment.weight} kg | ${initialShipment.volume} m³`);
  console.log(`  • Deadline:    ${initialShipment.deadline}\n`);

  // 2. Solve Recovery & Solver Status Assertion
  console.log(`[2. EXECUTING MOSAIC SOLVER]`);
  stateManager.solveRecovery(shipmentId);
  const plans = stateManager.getPlans(shipmentId);
  const receipt = stateManager.getReceipt(shipmentId);

  assert(receipt !== undefined, "Decision receipt must be generated by solver");
  assert(receipt.status === "OPTIMAL", `Solver must return OPTIMAL status (got: ${receipt.status})`);
  assert(receipt.feasibleCandidatesCount > 0, "Solver must discover at least 1 feasible candidate");
  assert(receipt.totalCandidatesEvaluated > 0, "Solver must evaluate positive candidate corridors");

  console.log(`  • Solver Status:        ${receipt.status}`);
  console.log(`  • Total Candidates:     ${receipt.totalCandidatesEvaluated}`);
  console.log(`  • Feasible Options:     ${receipt.feasibleCandidatesCount}`);
  console.log(`  • Rejected Count:       ${receipt.rejectedCandidates?.length ?? 0}\n`);

  // 3. Primary Plan Strict Assertion
  console.log(`[3. PRIMARY RECOVERY PLAN]`);
  const primaryPlan = plans.find((p) => p.strategy === "PRIMARY");
  assert(primaryPlan !== undefined, "Primary recovery plan MUST be generated and non-null");
  assert(primaryPlan.strategy === "PRIMARY", "Primary plan must have strategy PRIMARY");
  assert(typeof primaryPlan.vehicleId === "string" && primaryPlan.vehicleId.length > 0, "Primary plan must have a valid assigned vehicle");
  assert(primaryPlan.slaMarginMinutes >= 0, `Primary plan must satisfy delivery deadline (margin: ${primaryPlan.slaMarginMinutes} min)`);
  assert(primaryPlan.incrementalCost > 0, `Primary plan must have calculated positive incremental cost (₹${primaryPlan.incrementalCost})`);
  assert(typeof primaryPlan.co2SavedKg === "number" && primaryPlan.co2SavedKg > 0, "Primary plan must compute positive carbon avoidance");
  assert(typeof primaryPlan.costSavingsPercent === "number" && primaryPlan.costSavingsPercent > 0, "Primary plan must achieve positive savings vs charter");

  console.log(`  • Assigned Vehicle:     ${primaryPlan.vehicleId}`);
  console.log(`  • Transit Corridor:     ${primaryPlan.pickupHub} -> ${primaryPlan.dropoffHub}`);
  console.log(`  • Dropoff ETA:          ${primaryPlan.eta}`);
  console.log(`  • SLA Safety Buffer:    +${primaryPlan.slaMarginMinutes} min`);
  console.log(`  • Incremental Cost:     ₹${primaryPlan.incrementalCost.toLocaleString()}`);
  console.log(`  • Avoided Emissions:    ${primaryPlan.co2SavedKg} kg CO₂ (GLEC/ISO 14083 aligned)`);
  console.log(`  • Financial Savings:    ${primaryPlan.costSavingsPercent}% vs emergency charter\n`);

  // 4. Shadow Plan Strict Assertion & Fallback Guarantee
  console.log(`[4. SHADOW PLAN & FALLBACK GUARANTEE]`);
  const shadowPlan = plans.find((p) => p.strategy === "SHADOW");
  assert(shadowPlan !== undefined, "Shadow hot-standby plan MUST be generated and non-null");
  assert(shadowPlan.strategy === "SHADOW", "Shadow plan must have strategy SHADOW");
  assert(shadowPlan.vehicleId !== primaryPlan.vehicleId, "Shadow plan must utilize a non-identical vehicle fleet asset");
  assert(shadowPlan.shadowGuarantee !== undefined, "Shadow plan must carry a quantified shadow guarantee audit");
  assert(
    shadowPlan.shadowGuarantee.guarantee === "EDGE_DISJOINT" || shadowPlan.shadowGuarantee.guarantee === "PENALIZED_OVERLAP",
    `Shadow guarantee must be EDGE_DISJOINT or PENALIZED_OVERLAP (got: ${shadowPlan.shadowGuarantee.guarantee})`
  );
  assert(typeof shadowPlan.shadowGuarantee.overlapPercentage === "number", "Shadow plan must quantify overlap percentage");

  console.log(`  • Backup Vehicle:       ${shadowPlan.vehicleId}`);
  console.log(`  • Corridor:             ${shadowPlan.pickupHub} -> ${shadowPlan.dropoffHub}`);
  console.log(`  • Dropoff ETA:          ${shadowPlan.eta}`);
  console.log(`  • SLA Safety Buffer:    +${shadowPlan.slaMarginMinutes} min`);
  console.log(`  • Incremental Cost:     ₹${shadowPlan.incrementalCost.toLocaleString()}`);
  console.log(`  • Fallback Guarantee:   ${shadowPlan.shadowGuarantee.guarantee}`);
  console.log(`  • Overlap Percentage:   ${shadowPlan.shadowGuarantee.overlapPercentage}%`);
  console.log(`  • Shared Highway Km:    ${shadowPlan.shadowGuarantee.sharedDistanceKm} km`);
  console.log(`  • Audit Certification:  ${shadowPlan.shadowGuarantee.quantitativeAudit}\n`);

  // 5. Dynamic Replanning Strict Assertion
  console.log(`[5. DYNAMIC REPLANNING TEST]`);
  console.log(`  • Triggering Re-optimization for ${shipmentId}...`);
  stateManager.reoptimize(shipmentId);
  const reoptimizedPlans = stateManager.getPlans(shipmentId);
  const reoptimizedReceipt = stateManager.getReceipt(shipmentId);

  assert(reoptimizedPlans.length >= 2, `Dynamic replanning must reproduce both Primary and Shadow plans (got: ${reoptimizedPlans.length})`);
  assert(reoptimizedReceipt !== undefined, "Replanning must generate a new decision receipt");
  assert(typeof reoptimizedReceipt.hash === "string" && reoptimizedReceipt.hash.startsWith("0x"), "Decision receipt hash must be valid 256-bit hex string starting with 0x");
  assert(reoptimizedReceipt.hash.length === 66, "Decision receipt hash must be exactly 66 chars (0x + 64 hex characters)");

  console.log(`  • Replanning Completed in ${reoptimizedReceipt.solveTimeMs} ms`);
  console.log(`  • Re-evaluated Plans:   ${reoptimizedPlans.length} active plans`);
  console.log(`  • Receipt Hash:         ${reoptimizedReceipt.hash}\n`);

  console.log("========================================================================");
  console.log("  ALL RUNTIME ASSERTIONS PASSED WITH ZERO TOLERANCE FOR MISSING PLANS!");
  console.log("========================================================================");
}

verifyRecoveryPipeline().catch((err) => {
  console.error("\nFATAL ASSERTION ERROR:", err.message);
  process.exit(1);
});
